# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Arvid Leimar
title: .NET developer
email: arvid@leimar.se
website: www.github.com/pinkros

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username: pinkros
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: arvid-leimar-742212a3
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Arvid, and I'm currently trying to become a developer. I am attending a course as a .NET developer and will soon be ready for actual jobs.

  My main qualities include <mark>teamwork</mark>, <mark>.NET-development</mark> in <mark>C#</mark> and <mark>leadership</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Nccsv-parser
        link: https://github.com/snd-sweden/nccsv_netcdf
        # link_text: Project Website
        additional_links:
          - title: snd-sweden/nccsv_netcdf
            icon: fab fa-github
            url: github.com/snd-sweden/nccsv_netcdf
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A class library for the purpose of validation and conversion of [NCCSV-files](https://coastwatch.pfeg.noaa.gov/erddap/download/NCCSV.html)
        description: | # this will include new lines to allow paragraphs
        As a part of our internship at [SND](https://snd.gu.se/en/about-us), the Swedish National Data Service, we developed a class library to help validate and parse NCCSV-files. The library is meant to be implemented into other projects, as a way to make NCCSV more accessible.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wolters Kluwer Scandinavia
        link: https://www.wolterskluwer.com/sv-se
        link_text: wolterskluwer.com
        sub_title: Order Processing Representative
        caption: January 2020 - current
        quote: >
          Delivered software, invoices and sales support whilst wrestling with SAP
        description: | # this will include new lines to allow paragraphs

      - layout: left
        title: Wolters Kluwer Scandinavia
        link: https://www.wolterskluwer.com/sv-se
        link_text: wolterskluwer.com
        sub_title: Order Processing Representative
        caption: January 2020 - current
        quote: >
          Delivered software, invoices and sales support whilst wrestling SAP
        description: | # this will include new lines to allow paragraphs
          

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: IT-Högskolan
        link: https://www.iths.se/
        link-text: iths.se
        caption: 2022 - 2024
        sub_title: .NET-developer
        quote: >
          Your IT-career begins here!
        description: | # this will include new lines to allow paragraphs
          A [Higher Vocational Education](https://www.yrkeshogskolan.se/in-english/) with the purpose of quickly making it's students into full-fledged developers. I learned such skills as <mark>C#</mark>, database development with both <mark>SQL</mark> and <mark>NoSQL</mark>, web development with <mark>HTML</mark>, <mark>JavaScript</mark> and <mark>Blazor</mark>, working in projects with <mark>SCRUM</mark> among other things.

          I was elected class representative to be part of the *Education board* and was responsible for the class' shared *coffee fund*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
